[package]
name = "rust-onepunch"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_onepunch"
crate-type = ["cdylib", "staticlib"]

[dependencies]
libc = "0.2"

[build-dependencies]
cbindgen = "0.24"
